export const TODOS_FETCH_SUCCEEDED = 'TODOS_FETCH_SUCCEEDED';
export const TODO_CREATE_SUCCEEDED = 'TODO_CREATE_SUCCEEDDED';
export const TODO_UPDATE_SUCCEEDED = 'TODO_UPDATE_SUCCEEDDED';
export const TODO_DELETE_SUCCEEDED = 'TODO_DELETE_SUCCEEDDED';
